apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inbox-ms-v1
  labels:
    app: inbox-ms
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: inbox-ms
        version: v1
    spec:
      containers:
      - name: inbox-ms
        image: andreleoni/inbox-microservice:latest
        args: ["rails s -p 3001 -b 0.0.0.0"]
        imagePullPolicy: IfNotPresent
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: RAILS_SERVE_STATIC_FILES
          value: "true"
        - name: REDIS_URL
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: RAILS_ENV
          value: "production"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: "secret-key-base"
              key: "secret-key-base"
        ports:
        - containerPort: 3001
